// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by scripts/gen_airlines.py - do not edit by hand.
//
// ICAO airline designator to the name to show. The callsign the feed gives is an
// ICAO flight identifier - three letters of designator then the flight number -
// so the prefix is all this needs.
//
// The names are PROGMEM and so is the table, and the lookup copies into the
// caller's buffer. A PROGMEM table pointing at plain literals would read the
// pointer correctly and then fault on dereference the day the toolchain puts
// those literals in flash.
//
// Carriers absent from the list keep showing their raw callsign: a wrong airline
// name is worse than none.
#pragma once

#include <pgmspace.h>
#include <cstdint>
#include <cstring>

namespace Airlines {

constexpr size_t MAX_NAME = 25;   // longest name plus its terminator

const char N_AAL[] PROGMEM = "\xec\x95\x84\xeb\xa9\x94\xeb\xa6\xac\xec\xb9\xb8\xed\x95\xad\xea\xb3\xb5";   // 아메리칸항공
const char N_AAR[] PROGMEM = "\xec\x95\x84\xec\x8b\x9c\xec\x95\x84\xeb\x82\x98\xed\x95\xad\xea\xb3\xb5";   // 아시아나항공
const char N_ABL[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xeb\xb6\x80\xec\x82\xb0";   // 에어부산
const char N_ABW[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xeb\xb8\x8c\xeb\xa6\xac\xec\xa7\x80\xec\xb9\xb4\xea\xb3\xa0";   // 에어브리지카고
const char N_ACA[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xec\xba\x90\xeb\x82\x98\xeb\x8b\xa4";   // 에어캐나다
const char N_AFL[] PROGMEM = "\xec\x95\x84\xec\x97\x90\xeb\xa1\x9c\xed\x94\x8c\xeb\xa1\x9c\xed\x8a\xb8";   // 아에로플로트
const char N_AFR[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xed\x94\x84\xeb\x9e\x91\xec\x8a\xa4";   // 에어프랑스
const char N_AIC[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xec\x9d\xb8\xeb\x94\x94\xec\x95\x84";   // 에어인디아
const char N_ANA[] PROGMEM = "\xec\xa0\x84\xec\x9d\xbc\xeb\xb3\xb8\xea\xb3\xb5\xec\x88\x98";   // 전일본공수
const char N_APJ[] PROGMEM = "\xed\x94\xbc\xec\xb9\x98\xed\x95\xad\xea\xb3\xb5";   // 피치항공
const char N_APZ[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xed\x94\x84\xeb\xa0\x88\xeb\xaf\xb8\xec\x95\x84";   // 에어프레미아
const char N_ASV[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xec\x84\x9c\xec\x9a\xb8";   // 에어서울
const char N_BAW[] PROGMEM = "\xeb\xb8\x8c\xeb\xa6\xac\xed\x8b\xb0\xec\x8b\x9c\xed\x95\xad\xea\xb3\xb5";   // 브리티시항공
const char N_CAL[] PROGMEM = "\xec\xa4\x91\xed\x99\x94\xed\x95\xad\xea\xb3\xb5";   // 중화항공
const char N_CCA[] PROGMEM = "\xec\xa4\x91\xea\xb5\xad\xea\xb5\xad\xec\xa0\x9c\xed\x95\xad\xea\xb3\xb5";   // 중국국제항공
const char N_CES[] PROGMEM = "\xec\xa4\x91\xea\xb5\xad\xeb\x8f\x99\xeb\xb0\xa9\xed\x95\xad\xea\xb3\xb5";   // 중국동방항공
const char N_CHH[] PROGMEM = "\xed\x95\x98\xec\x9d\xb4\xeb\x82\x9c\xed\x95\xad\xea\xb3\xb5";   // 하이난항공
const char N_CLX[] PROGMEM = "\xec\xb9\xb4\xea\xb3\xa0\xeb\xa3\xa9\xec\x8a\xa4";   // 카고룩스
const char N_CPA[] PROGMEM = "\xec\xba\x90\xec\x84\xb8\xec\x9d\xb4\xed\x8d\xbc\xec\x8b\x9c\xed\x94\xbd";   // 캐세이퍼시픽
const char N_CSN[] PROGMEM = "\xec\xa4\x91\xea\xb5\xad\xeb\x82\xa8\xeb\xb0\xa9\xed\x95\xad\xea\xb3\xb5";   // 중국남방항공
const char N_DAL[] PROGMEM = "\xeb\x8d\xb8\xed\x83\x80\xed\x95\xad\xea\xb3\xb5";   // 델타항공
const char N_DLH[] PROGMEM = "\xeb\xa3\xa8\xed\x94\x84\xed\x8a\xb8\xed\x95\x9c\xec\x9e\x90";   // 루프트한자
const char N_EOK[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xeb\xa1\x9c\xec\xbc\x80\xec\x9d\xb4";   // 에어로케이
const char N_ESR[] PROGMEM = "\xec\x9d\xb4\xec\x8a\xa4\xed\x83\x80\xed\x95\xad\xea\xb3\xb5";   // 이스타항공
const char N_ETD[] PROGMEM = "\xec\x97\x90\xed\x8b\xb0\xed\x95\x98\xeb\x93\x9c";   // 에티하드
const char N_EVA[] PROGMEM = "\xec\x97\x90\xeb\xb0\x94\xed\x95\xad\xea\xb3\xb5";   // 에바항공
const char N_FDX[] PROGMEM = "\xed\x8e\x98\xeb\x8d\xb1\xec\x8a\xa4";   // 페덱스
const char N_FIN[] PROGMEM = "\xed\x95\x80\xec\x97\x90\xec\x96\xb4";   // 핀에어
const char N_GIA[] PROGMEM = "\xea\xb0\x80\xeb\xa3\xa8\xeb\x8b\xa4\xec\x9d\xb8\xeb\x8f\x84\xeb\x84\xa4\xec\x8b\x9c\xec\x95\x84";   // 가루다인도네시아
const char N_GTI[] PROGMEM = "\xec\x95\x84\xed\x8b\x80\xeb\x9d\xbc\xec\x8a\xa4\xed\x95\xad\xea\xb3\xb5";   // 아틀라스항공
const char N_HVN[] PROGMEM = "\xeb\xb2\xa0\xed\x8a\xb8\xeb\x82\xa8\xed\x95\xad\xea\xb3\xb5";   // 베트남항공
const char N_JAL[] PROGMEM = "\xec\x9d\xbc\xeb\xb3\xb8\xed\x95\xad\xea\xb3\xb5";   // 일본항공
const char N_JJA[] PROGMEM = "\xec\xa0\x9c\xec\xa3\xbc\xed\x95\xad\xea\xb3\xb5";   // 제주항공
const char N_JNA[] PROGMEM = "\xec\xa7\x84\xec\x97\x90\xec\x96\xb4";   // 진에어
const char N_KAL[] PROGMEM = "\xeb\x8c\x80\xed\x95\x9c\xed\x95\xad\xea\xb3\xb5";   // 대한항공
const char N_KLM[] PROGMEM = "\xec\xbc\x80\xec\x9d\xb4\xec\x97\x98\xec\x97\xa0";   // 케이엘엠
const char N_MAS[] PROGMEM = "\xeb\xa7\x90\xeb\xa0\x88\xec\x9d\xb4\xec\x8b\x9c\xec\x95\x84\xed\x95\xad\xea\xb3\xb5";   // 말레이시아항공
const char N_PAL[] PROGMEM = "\xed\x95\x84\xeb\xa6\xac\xed\x95\x80\xed\x95\xad\xea\xb3\xb5";   // 필리핀항공
const char N_QTR[] PROGMEM = "\xec\xb9\xb4\xed\x83\x80\xeb\xa5\xb4\xed\x95\xad\xea\xb3\xb5";   // 카타르항공
const char N_SIA[] PROGMEM = "\xec\x8b\xb1\xea\xb0\x80\xed\x8f\xac\xeb\xa5\xb4\xed\x95\xad\xea\xb3\xb5";   // 싱가포르항공
const char N_SKY[] PROGMEM = "\xec\x8a\xa4\xec\xb9\xb4\xec\x9d\xb4\xeb\xa7\x88\xed\x81\xac";   // 스카이마크
const char N_SVA[] PROGMEM = "\xec\x82\xac\xec\x9a\xb0\xeb\x94\x94\xec\x95\x84\xed\x95\xad\xea\xb3\xb5";   // 사우디아항공
const char N_SWR[] PROGMEM = "\xec\x8a\xa4\xec\x9c\x84\xec\x8a\xa4\xed\x95\xad\xea\xb3\xb5";   // 스위스항공
const char N_THA[] PROGMEM = "\xed\x83\x80\xec\x9d\xb4\xed\x95\xad\xea\xb3\xb5";   // 타이항공
const char N_THY[] PROGMEM = "\xed\x84\xb0\xed\x82\xa4\xed\x95\xad\xea\xb3\xb5";   // 터키항공
const char N_TWB[] PROGMEM = "\xed\x8b\xb0\xec\x9b\xa8\xec\x9d\xb4\xed\x95\xad\xea\xb3\xb5";   // 티웨이항공
const char N_UAE[] PROGMEM = "\xec\x97\x90\xeb\xaf\xb8\xeb\xa0\x88\xec\x9d\xb4\xed\x8a\xb8";   // 에미레이트
const char N_UAL[] PROGMEM = "\xec\x9c\xa0\xeb\x82\x98\xec\x9d\xb4\xed\x8b\xb0\xeb\x93\x9c\xed\x95\xad\xea\xb3\xb5";   // 유나이티드항공
const char N_UPS[] PROGMEM = "\xec\x9c\xa0\xed\x94\xbc\xec\x97\x90\xec\x8a\xa4";   // 유피에스

struct Entry {
    char code[4];
    const char* name;
};

const Entry TABLE[] PROGMEM = {
    {"AAL", N_AAL},
    {"AAR", N_AAR},
    {"ABL", N_ABL},
    {"ABW", N_ABW},
    {"ACA", N_ACA},
    {"AFL", N_AFL},
    {"AFR", N_AFR},
    {"AIC", N_AIC},
    {"ANA", N_ANA},
    {"APJ", N_APJ},
    {"APZ", N_APZ},
    {"ASV", N_ASV},
    {"BAW", N_BAW},
    {"CAL", N_CAL},
    {"CCA", N_CCA},
    {"CES", N_CES},
    {"CHH", N_CHH},
    {"CLX", N_CLX},
    {"CPA", N_CPA},
    {"CSN", N_CSN},
    {"DAL", N_DAL},
    {"DLH", N_DLH},
    {"EOK", N_EOK},
    {"ESR", N_ESR},
    {"ETD", N_ETD},
    {"EVA", N_EVA},
    {"FDX", N_FDX},
    {"FIN", N_FIN},
    {"GIA", N_GIA},
    {"GTI", N_GTI},
    {"HVN", N_HVN},
    {"JAL", N_JAL},
    {"JJA", N_JJA},
    {"JNA", N_JNA},
    {"KAL", N_KAL},
    {"KLM", N_KLM},
    {"MAS", N_MAS},
    {"PAL", N_PAL},
    {"QTR", N_QTR},
    {"SIA", N_SIA},
    {"SKY", N_SKY},
    {"SVA", N_SVA},
    {"SWR", N_SWR},
    {"THA", N_THA},
    {"THY", N_THY},
    {"TWB", N_TWB},
    {"UAE", N_UAE},
    {"UAL", N_UAL},
    {"UPS", N_UPS},
};
constexpr uint8_t COUNT = 49;

// Fills `out` and returns true when the prefix is known; leaves it empty and
// returns false otherwise, which the caller shows as the bare callsign.
inline bool nameFor(const char* callsign, char* out, size_t size) {
    if (out == nullptr || size == 0) return false;
    out[0] = 0;
    if (callsign == nullptr) return false;
    for (uint8_t i = 0; i < 3; ++i) {
        if (callsign[i] < 'A' || callsign[i] > 'Z') return false;
    }
    for (uint8_t i = 0; i < COUNT; ++i) {
        Entry entry{};
        memcpy_P(&entry, &TABLE[i], sizeof(Entry));
        if (entry.code[0] != callsign[0] || entry.code[1] != callsign[1] ||
            entry.code[2] != callsign[2]) {
            continue;
        }
        strncpy_P(out, entry.name, size - 1);
        out[size - 1] = 0;
        return true;
    }
    return false;
}

}  // namespace Airlines
