// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by scripts/gen_airlines.py - do not edit by hand.
//
// ICAO type designator to the rotorcraft name to show. A helicopter almost never
// carries an airline designator, so the line that names the carrier for an airliner
// names the machine instead. The feed gives the type code directly.
//
// The names are PROGMEM and so is the table, and the lookup copies into the
// caller's buffer. A PROGMEM table pointing at plain literals would read the
// pointer correctly and then fault on dereference the day the toolchain puts
// those literals in flash.
//
// Types absent from the list keep showing their bare code, which is still useful
// and cannot be wrong.
#pragma once

#include <pgmspace.h>
#include <cstdint>
#include <cstring>

namespace Rotorcraft {

constexpr size_t MAX_NAME = 18;   // longest name plus its terminator

const char T_A109[] PROGMEM = "\xec\x95\x84\xea\xb5\xac\xec\x8a\xa4\xed\x83\x80\x31\x30\x39";   // 아구스타109
const char T_A139[] PROGMEM = "\xec\x95\x84\xea\xb5\xac\xec\x8a\xa4\xed\x83\x80\x31\x33\x39";   // 아구스타139
const char T_A169[] PROGMEM = "\xec\x95\x84\xea\xb5\xac\xec\x8a\xa4\xed\x83\x80\x31\x36\x39";   // 아구스타169
const char T_A189[] PROGMEM = "\xec\x95\x84\xea\xb5\xac\xec\x8a\xa4\xed\x83\x80\x31\x38\x39";   // 아구스타189
const char T_AH1[] PROGMEM = "\xec\xbd\x94\xeb\xb8\x8c\xeb\x9d\xbc";   // 코브라
const char T_AH64[] PROGMEM = "\xec\x95\x84\xed\x8c\x8c\xec\xb9\x98";   // 아파치
const char T_AS50[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xeb\xb2\x84\xec\x8a\xa4\x48\x31\x32\x35";   // 에어버스H125
const char T_AS65[] PROGMEM = "\xeb\x8f\x8c\xed\x95\x80";   // 돌핀
const char T_B06[] PROGMEM = "\xeb\xb2\xa8\x32\x30\x36";   // 벨206
const char T_B407[] PROGMEM = "\xeb\xb2\xa8\x34\x30\x37";   // 벨407
const char T_B412[] PROGMEM = "\xeb\xb2\xa8\x34\x31\x32";   // 벨412
const char T_B429[] PROGMEM = "\xeb\xb2\xa8\x34\x32\x39";   // 벨429
const char T_B430[] PROGMEM = "\xeb\xb2\xa8\x34\x33\x30";   // 벨430
const char T_B505[] PROGMEM = "\xeb\xb2\xa8\x35\x30\x35";   // 벨505
const char T_BK17[] PROGMEM = "\xec\x9c\xa0\xeb\xa1\x9c\xec\xbd\xa5\xed\x84\xb0\x31\x31\x37";   // 유로콥터117
const char T_CH47[] PROGMEM = "\xec\xb9\x98\xeb\x88\x84\xed\x81\xac";   // 치누크
const char T_EC20[] PROGMEM = "\xec\x9c\xa0\xeb\xa1\x9c\xec\xbd\xa5\xed\x84\xb0\x31\x32\x30";   // 유로콥터120
const char T_EC30[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xeb\xb2\x84\xec\x8a\xa4\x48\x31\x33\x30";   // 에어버스H130
const char T_EC35[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xeb\xb2\x84\xec\x8a\xa4\x48\x31\x33\x35";   // 에어버스H135
const char T_EC45[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xeb\xb2\x84\xec\x8a\xa4\x48\x31\x34\x35";   // 에어버스H145
const char T_EC55[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xeb\xb2\x84\xec\x8a\xa4\x48\x31\x35\x35";   // 에어버스H155
const char T_EH10[] PROGMEM = "\xeb\xa9\x80\xeb\xa6\xb0";   // 멀린
const char T_H125[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xeb\xb2\x84\xec\x8a\xa4\x48\x31\x32\x35";   // 에어버스H125
const char T_H130[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xeb\xb2\x84\xec\x8a\xa4\x48\x31\x33\x30";   // 에어버스H130
const char T_H135[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xeb\xb2\x84\xec\x8a\xa4\x48\x31\x33\x35";   // 에어버스H135
const char T_H145[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xeb\xb2\x84\xec\x8a\xa4\x48\x31\x34\x35";   // 에어버스H145
const char T_H155[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xeb\xb2\x84\xec\x8a\xa4\x48\x31\x35\x35";   // 에어버스H155
const char T_H160[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xeb\xb2\x84\xec\x8a\xa4\x48\x31\x36\x30";   // 에어버스H160
const char T_H175[] PROGMEM = "\xec\x97\x90\xec\x96\xb4\xeb\xb2\x84\xec\x8a\xa4\x48\x31\x37\x35";   // 에어버스H175
const char T_H500[] PROGMEM = "\xed\x9c\xb4\xec\xa6\x88\x35\x30\x30";   // 휴즈500
const char T_H60[] PROGMEM = "\xeb\xb8\x94\xeb\x9e\x99\xed\x98\xb8\xed\x81\xac";   // 블랙호크
const char T_KUH1[] PROGMEM = "\xec\x88\x98\xeb\xa6\xac\xec\x98\xa8";   // 수리온
const char T_LYNX[] PROGMEM = "\xeb\xa7\x81\xec\x8a\xa4";   // 링스
const char T_MD50[] PROGMEM = "\xed\x9c\xb4\xec\xa6\x88\x35\x30\x30";   // 휴즈500
const char T_MI17[] PROGMEM = "\xeb\xaf\xb8\x2d\x31\x37";   // 미-17
const char T_MI8[] PROGMEM = "\xeb\xaf\xb8\x2d\x38";   // 미-8
const char T_R22[] PROGMEM = "\xeb\xa1\x9c\xeb\xb9\x88\xec\x8a\xa8\x32\x32";   // 로빈슨22
const char T_R44[] PROGMEM = "\xeb\xa1\x9c\xeb\xb9\x88\xec\x8a\xa8\x34\x34";   // 로빈슨44
const char T_R66[] PROGMEM = "\xeb\xa1\x9c\xeb\xb9\x88\xec\x8a\xa8\x36\x36";   // 로빈슨66
const char T_S70[] PROGMEM = "\xeb\xb8\x94\xeb\x9e\x99\xed\x98\xb8\xed\x81\xac";   // 블랙호크
const char T_S76[] PROGMEM = "\xec\x8b\x9c\xec\xbd\x94\xeb\xa5\xb4\xec\x8a\xa4\xed\x82\xa4\x37\x36";   // 시코르스키76
const char T_S92[] PROGMEM = "\xec\x8b\x9c\xec\xbd\x94\xeb\xa5\xb4\xec\x8a\xa4\xed\x82\xa4\x39\x32";   // 시코르스키92
const char T_SH60[] PROGMEM = "\xec\x8b\x9c\xed\x98\xb8\xed\x81\xac";   // 시호크
const char T_UH1[] PROGMEM = "\xed\x9c\xb4\xec\x9d\xb4";   // 휴이

struct Entry {
    char code[5];
    const char* name;
};

const Entry TABLE[] PROGMEM = {
    {"A109", T_A109},
    {"A139", T_A139},
    {"A169", T_A169},
    {"A189", T_A189},
    {"AH1", T_AH1},
    {"AH64", T_AH64},
    {"AS50", T_AS50},
    {"AS65", T_AS65},
    {"B06", T_B06},
    {"B407", T_B407},
    {"B412", T_B412},
    {"B429", T_B429},
    {"B430", T_B430},
    {"B505", T_B505},
    {"BK17", T_BK17},
    {"CH47", T_CH47},
    {"EC20", T_EC20},
    {"EC30", T_EC30},
    {"EC35", T_EC35},
    {"EC45", T_EC45},
    {"EC55", T_EC55},
    {"EH10", T_EH10},
    {"H125", T_H125},
    {"H130", T_H130},
    {"H135", T_H135},
    {"H145", T_H145},
    {"H155", T_H155},
    {"H160", T_H160},
    {"H175", T_H175},
    {"H500", T_H500},
    {"H60", T_H60},
    {"KUH1", T_KUH1},
    {"LYNX", T_LYNX},
    {"MD50", T_MD50},
    {"MI17", T_MI17},
    {"MI8", T_MI8},
    {"R22", T_R22},
    {"R44", T_R44},
    {"R66", T_R66},
    {"S70", T_S70},
    {"S76", T_S76},
    {"S92", T_S92},
    {"SH60", T_SH60},
    {"UH1", T_UH1},
};
constexpr uint8_t COUNT = 44;

// Fills `out` and returns true when the prefix is known; leaves it empty and
// returns false otherwise, which the caller shows as the bare type code.
inline bool nameFor(const char* type, char* out, size_t size) {
    if (out == nullptr || size == 0) return false;
    out[0] = 0;
    if (type == nullptr) return false;
    for (uint8_t i = 0; i < COUNT; ++i) {
        Entry entry{};
        memcpy_P(&entry, &TABLE[i], sizeof(Entry));
        if (strcmp(entry.code, type) != 0) continue;
        strncpy_P(out, entry.name, size - 1);
        out[size - 1] = 0;
        return true;
    }
    return false;
}

// Whether the table recognises this code, without copying the name. The
// parser asks this of every aircraft in a reply just to decide what to draw,
// and a lookup that answers a question it was not asked is a lookup that
// says the wrong thing about its own purpose.
inline bool knows(const char* type) {
    if (type == nullptr || type[0] == 0) return false;
    for (uint8_t i = 0; i < COUNT; ++i) {
        Entry entry{};
        memcpy_P(&entry, &TABLE[i], sizeof(Entry));
        if (strcmp(entry.code, type) == 0) return true;
    }
    return false;
}

}  // namespace Rotorcraft
